apiVersion: v1
kind: Pod
metadata:
  name: mongo
  namespace: gojobs
  labels:
     app: mongo    
spec:
    containers:
    - name: mongo
      image: registry.ckmro.com:1180/library/mongo
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 27017
      volumeMounts:
      - name: mongo-storage
        mountPath: /data/db
    volumes:
      - name: mongo-storage
        hostPath:
          path: /data/db
    imagePullSecrets:
      - name: harborsecret
    restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: gojobs
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: mongo
  ports:
    - port: 27017
      nodePort: 32017